export default function Essay() {
    return (
        <div className="essay">
            <h3 className="essay-heading">Essay (Around 500 Words)</h3>
            <p className="essay-text">Project 3 has given more gravity and quality to the idea of project 2 and extended it in such a way that makes people wonder what can be achieved through Virtual Reality(VR). The Mego Playset version presents how components of a complicated and comprehensive environment can be updated, rearranged, and even improved by scaling the situation to a diminutive one, and in this way, the user can handle all of the conditions within the palms of his/her hands. The Land of Giants perspective reveals us a perspective where the user can interact with objects that are quite trivial to interact within a normal perspective. Dancing on the Ceiling perspective demonstrates how the user’s viewpoint and movements can be affected by just revolving around the whole environment. Finally, the Zero-Gravity perspective provides the user a simple and significant way to navigate in an environment where walking is just not feasible. <br/>
In the applications of planning, structuring, and architecting, the architects and engineers generally have a model or miniature version of their desired product. This model is to check and show other people the work they have accomplished or to display what the genuine outcome would resemble. But in the real world, the physical models are not pragmatic and lack a lot of information. For example, designing a restaurant would need an architect to develop a physical model of a restaurant but still the architect cannot demonstrate lightings, audio, how people would sit in the restaurant, the ambiance, and many more external factors. The Mego Playset version of Project 2 gives a brief demonstration of what that architect can achieve by just replacing real models with virtual ones and creating a virtual environment instead of an artificial model. Physics Engines like Unity and Unreal Engine are very apt in replicating the real-world environment in terms of visuals, audios, animations, and interactions. The idea of presenting a virtual world to the supervisors and letting others experience the virtual world of your sought product will make the whole thing more appealing. It is capable of providing an immersive experience rather than just having a demonstration. <br/>
The Land of the Giants perspective will be extremely helpful in scenarios associated with the exploration of a virtual world. Let us take the example of planet Mars. Scientists around the globe are trying to find whether life can be sustained on Mars or not. Unfortunately, this question has not been answered but with the help of VR, advancements can be made in exploring the surface of Mars. With a perspective like Land of the Giants, users can visualize and study minute objects on the surface of Mars. One of the other applications can be exploring insects and micro-organisms. People have been studying microorganisms and insects with the help of microscopes and ultra-zoom cameras. However, a detailed VR perspective can help gain more insights into their behaviors. <br/>
Virtual Reality is so immersive that it makes our brain believe that the virtual environment is real and we experience anomalies in the virtual world as they are happening in real. This level of immersion can help educate and aware souls of real-life calamities. The Dancing on the Ceiling tries to simulate a world where the environment rotates and the whole experience is very surreal and terrifying at the same time. The situations like earthquakes, breakdown of a building, etc can be simulated with similar experiences. In the majority of the places where human life is abundant, there is also a risk of earthquakes. This kind of simulation can help people learn about how to behave in such circumstances. People can learn that if a similar situation ever arrives in the real world, they would know how to act. This is a nice way of teaching survival in any natural or man-made catastrophe. <br/>
Finally, zero-gravity in VR is one of the ways to help astronauts experience zero-gravity. The ability of Unity to add forces that are governed by real-world physics accurately replicates the zero-gravity situation even in a virtual simulation. Zero-gravity is also a fun experience that people find amusing. This perspective can even be helpful in gaming as well. <br/>
All of these experiences are bound with the help of an interactive menu. A presence of a menu or a control system can help the user control the navigation of the whole experience. All of these perspectives can be utilized together to create an environment for heterogeneous perspectives where multiple users can interact with the environment with different scales and have their own set of tools to operate in their own space. The possibilities and applications are endless if we start thinking about VR’s caliber. <br/>
</p>
        </div>
    );
}