export default function Essay() {
    return (
        <div className="essay">
            <h3 className="essay-heading">What does the future looks like? (Around 500 words Essay)</h3>
            <p className="essay-text">The Knickknacks created as part of this project are actually very smart as it brings a lot more to reality than a normal real-object knickknack. And yes, it can only be experienced through an Augmented Reality (AR) or a Virtual Reality (VR) supporting software running on a machine or device that supports AR/VR capabilities. But since the AR and VR domains are expanding at a fast pace, and we are including these elements in our day-to-day life (in software like Snapchat, Instagram and in AR/VR enabled games). This means that our world has welcomed the concept of mixed reality and the day is not far when people will start experiencing these technologies just like a normal habit like eating or sleeping. The question is that in a distant future, is it possible for people to replace real objects with virtual ones (like our knickknacks)?
            <br />
Lets take an example of our knickknacks, it has the capabilities to share real time weather information about the place it is relevant to, it can also work as a magic 8 Ball, plays audio which can bring that place’s memories back, and it also has the ability to animate virtual models which makes the whole knickknack more lively and playful. However, this is just an example which scratches only the surfaces of AR enabled technologies. Integrating with advanced technologies like voice recognition, Artificial Intelligence, Computer Vision, and Computer Graphics will become very easy in the future. So, a simple looking real-world object would be capable of performing tasks like playing videos and audios on the go, browsing the internet, playing games, interacting with virtual space and its objects, and doing pretty much anything that only computers or smartphones are capable of doing now, will eventually become more popular and common. With the ability to controls the behaviour of an AR object, it is highly likely that these objects will live among us and we will be highly dependent upon them. Virtual Objects in real life always look cool and they do impress people by how technology can change world, but people can get real annoyed if models are less interactive, low controllability, generates annoying sounds, glitches in visibility, and are of low detail. Although, since, we are talking of future, with a steep rise in computational capabilities of electronic devices, the probability that AR and VR might overcome the discrepancies mentioned previously.
<br />
The ways things are moving in the virtual world, we can predict or think about how our future will be affected by these technologies. Let us assume that we want to change the way we interact with a computer in future. An advanced system would replace the real keyboards, mouse and even monitors with virtual ones. They can simulate keyboard key/mouse click sounds, sense amount of pressure on the keys with features even better than real ones. User will be able to maximize and minimize videos to desired extent with just a slide of a finger. Also, video games these days are getting really advanced, and gamers have started trending custom gaming avatars and custom-made equipment (like guns and knives in Counter Strike: Go). Imagine experiencing these avatars placed on top of our own body. It will be a pivotal point in history for fashion industry. Even our cars can have an AR based skin. We can even use AR tech to replace watches, jewellery, and most of the decorative items in our home and workplaces. Finally, learning is part of our life, and with AR and VR, it can be possible to learn concepts of physics, chemistry, biology, etc visually, with the help of virtual objects. We will be able to make people understand conceptuality of experiments that are not possible without buying expensive apparatus. These are just few examples, but the possibilities are endless and these are really exciting.
</p>
        </div>
    );
}